### ISSUE TITLE
Improvement Request : Service Volume Datastore

### ISSUE THREAD

**Issue by larsy1** [BaldMansMojo/check_vmware_esx#111]
Hello all,

We are checking one Datastore Volume and is working fine :
`./check_vmware_esx.pl -H 51.254.40.143 --authfile=/srv/eyesofnetwork/nagios/plugins/vcenter_credential.txt -S volumes -s pcc-003467 -w 80% -c 90% --usedspace`

And the output is also fine :
```
OK: OK for selected volume(s).
Volumes above thresholds:
------------------------------------------------
Volumes below thresholds:
pcc-003467 (NFS) used: 19561.22 MB (6.98%) / 280191.23 MB (100%)
|'pcc-003467'=19561.22MB;224152.98;252172.11;;280191.23
```

But someone uninstall pcc-003467 Datastore, without warning anyone,  and now the output is less fine.

```
OK: OK for selected volume(s).
Volumes above thresholds:
------------------------------------------------
Volumes below thresholds:
```

the improvement request is : 
Is it possible to output the result in critical state when datastore is not found in order to detect a potential change in volume datastore config?

Any way, good job.

**Comment by BaldMansMojo** [comment]
Definetely a bug. I will fix it as soon as possible. I have to do a lot of other work too but I had not enough time during the last months.

Regards

**Comment by larsy1** [comment]
Hello BaldMansMojo,

Fyi,

When we use critical or warning parameter, problem is here.
```
./check_vmware_esx.pl -H 51.254.40.143 --authfile=/srv/eyesofnetwork/nagios/plugins/vcenter_credential.txt -S volumes -s pcc-00596  -w 80% -c 90% --usedspace
OK: OK for selected volume(s).
Volumes above thresholds:
------------------------------------------------
Volumes below thresholds:
```

When we don t use critical or warning parameter, the check is working.
```
./check_vmware_esx.pl -H 51.254.40.143 --authfile=/srv/eyesofnetwork/nagios/plugins/vcenter_credential.txt -S volumes -s pcc-00596  --usedspace
WARNING: No volume named "pcc-00596" found
```

I would propose a patch but I am afraid to do regression code.
thanks for your Pretty and Clear code

**Comment by larsy1** [comment]
Hello BaldMansMojo,

Did you have time to find a fix for this bug ?

Best Regards,

**Comment by BaldMansMojo** [comment]
Just back from vacation and desk full of senseless stuff

**Comment by fledorze** [comment]
Hello, any idea to fix this problem ?

**Comment by MaBauMeBad** [comment]
Same issue here... Would be very happy to see a Patch.
I would do it myself, but your Script is to complex for me ;)

**Comment by BaldMansMojo** [comment]
Fixed. Should work with latest release now.

regards
Martin
