### ISSUE TITLE
--statelabels argument not working

### ISSUE THREAD

**Issue by sRlinux** [BaldMansMojo/check_vmware_esx#114]
This is not working for me. 

It always give:
Option statelabels does not take an argument
as return

thx!

**Comment by BaldMansMojo** [comment]
I'll check it next week.

**Comment by BaldMansMojo** [comment]
Sorry for the laaaaaaaaate answer. Do you have an example?

**Comment by BaldMansMojo** [comment]
Got no answer so I close it.
