### ISSUE TITLE
Saved sessions not being re-used

### ISSUE THREAD

**Issue by philipowen** [BaldMansMojo/check_vmware_esx#115]
I'm seeing an issue where saved sessions are being ignored so a new session is being opened to the web service URL for every request. This is causing a very high number of active sessions to be reported by VMWare as they take 30 minutes to time out.

The issue seems to relate to line 1768 of check_vmware_esx.pl. Where `$url2connect` is being compared with the url option. Where no VI_URL env is specified the get_option call is constructing the URL differently to that which `$url2connect` uses. That results in a new session being created.

In my plugin execution I am specifying the datacenter as an IP and the port number so `$url2connect` gets populated with `https://1.2.3.4:443/sdk/webService` whereas the return from get_option is yielding `https://1.2.3.4/sdk` hence the test fails and the saved session is ignored.

**Comment by BaldMansMojo** [comment]
a) Which version of the SDK?
b) Can you give me a sample how you call the plugin?

**Comment by philipowen** [comment]
a) Now you mention it, it seems to be SDK 6.5 which I know isn't the advised one.
b) 
```
'./check_vmware_esx.pl' '--datacenter' '1.2.3.4' '--password' '********' '--select' 'net' '--sessionfiledir' '/var/spool/icinga2/tmp' '--sslport' '443' '--subselect' 'nic' '-H' '5.6.7.8' '--timeout' '90' '--username' '********'
```

**Comment by schindlerd** [comment]
Is this the same as #79 ?
Would my pull request #99 fix the problem?

**Comment by philipowen** [comment]
Yes @schindlerd it is a duplicate. I should have looked harder. PR #99 is exactly how I fixed it locally as I could not see what  value the comparison was adding.
