### ISSUE TITLE
Execution times out

### ISSUE THREAD

**Issue by SamBSolveIT** [BaldMansMojo/check_vmware_esx#116]
I have an issue with the Perl SDK - basically it does nothing. It'll eventually time out. I've reached out on the VMware community but no one seems to want to help. 

Is there any way to debug this so I can see exactly where the problem lies?

Thanks

**Comment by BaldMansMojo** [comment]
Follow the installation instructions. Use SDK 5.x. 6.x contains some bugs and is currently not needed by the plugin. Enclosed with the SDK are the command line tools. Use this tools to first test. Follow the documentaion which comes with the plugin. Aou need a local user on each VMware server who can see all  but can't change anything. There are several howtos on the web and on the VMware website. If testing with the CLI works the plugin should work too.

Regards - Martin
