### ISSUE TITLE
Wrong UOM in perfdata return --select io

### ISSUE THREAD

**Issue by andyflint** [BaldMansMojo/check_vmware_esx#118]
Hi,
In the select io module the return UOM (unit of measurement) for performance data ist "KB/s" instead of none.
Regards,
Andy

**Comment by bunghi** [comment]
I am facing the same problem. Any solution?

**Comment by BaldMansMojo** [comment]
Yep - but I had not the time to find a sufficient solution. All perfdata were used as they were in the old check_esx.pl. So if I change it the collected perfdata of thousands of installed systems will gone. I think I will implement a switch via option. But I had not the time to do it. It is "a little bit" difficult to fix.

**Comment by BaldMansMojo** [comment]
Fixed.
