### ISSUE TITLE
nagios  show "null" on interface

### ISSUE THREAD

**Issue by carmelotoner** [BaldMansMojo/check_vmware_esx#124]
Hi BaldMansMojo,

I try to use the plugin for our datacenter. In command line, it works great and show output results.

exemple command:
[root@nagios-01 check_vmware_esx-master]# ./check_vmware_esx.pl -D vcentritinf01tn.ftoma.mg --sessionfile=nagios.session --sessionfiledir=/srv/eyesofnetwork/nagios/plugins/check_vmware_esx-master/ --authfile=/srv/eyesofnetwork/nagios/plugins/check_vmware_esx-master/auth -C Orange -S runtime -s listhost
OK: 0/4 Hosts up: 192.168.15.225(UP), 192.168.15.50(UP), 192.168.15.199(UP), 192.168.15.226(UP)|vmcount=0;;;;

But in my nagios web interface, it shows always "CRITICAL" and in the results "null" when configured to be a service.
![image](https://user-images.githubusercontent.com/28706274/30913680-bc240a94-a399-11e7-88c7-e148327f9f02.png)

Have you some tricks to debug this?

Thanks for your hard works.

**Comment by BaldMansMojo** [comment]
So the plugin is ok and you have a nagios problem. I think it doesn't has anything to do with the plugin. According to your message you tested the plugin as root. But I assume your nagios is not running as root. Remeber: Always test plugins as the same user the monitoring demon is running.

**Comment by carmelotoner** [comment]
the same as nagios running user.
But i will check nagios then.
Thank you very much.

**Comment by BaldMansMojo** [comment]
Sure with the user? Example from you looks like using root. And Nagios uses nagios as default.

**Comment by carmelotoner** [comment]
yes Sir,

[root@nagios-01 check_vmware_esx-master]# su - nagios
[nagios@nagios-01 ~]$ cd /srv/eyesofnetwork/nagios/plugins/check_vmware_esx-master
[nagios@nagios-01 check_vmware_esx-master]$ ./check_vmware_esx.pl -D vcentritinf01tn.ftoma.mg --sessionfile=nagios.session --sessionfiledir=/srv/eyesofnetwork/nagios/plugins/check_vmware_esx-master/ --authfile=/srv/eyesofnetwork/nagios/plugins/check_vmware_esx-master/auth -C Orange -S runtime -s listhost
OK: 0/4 Hosts up: 192.168.15.225(UP), 192.168.15.50(UP), 192.168.15.199(UP), 192.168.15.226(UP)|vmcount=0;;;;

All option i used are translated to "CRITICAL" state and "null" on interface side.

**Comment by BaldMansMojo** [comment]
1)Ok. Have you checked the return code from the comman line (echo $?) after executing? Should be 0. 
2)When using it from Nagios you won't change to the dirctory and execute it. Do it from somewhere with full path and test.

Your problem has nothing to do with any option. It's either the way you call it from Nagios or something in you configuration is wrong.

**Comment by carmelotoner** [comment]
Thank you for your answers.
1) The return code is 0 
2) i will check for all my configurations. 

Thank you Sir.

regards,

**Comment by BaldMansMojo** [comment]
So with 0 it is completely clear. it's not the plugin causing the trouble.

Good luck
