### ISSUE TITLE
Undefined subroutine &Util::connect called at check_vmware_esx.pl line 1675.

### ISSUE THREAD

**Issue by vercetty92360** [BaldMansMojo/check_vmware_esx#131]
Hi,

When I launch the script either using "-u + -p" or "-f", I have the following error:

Undefined subroutine &Util::connect called at check_vmware_esx.pl line 1675.

Do you know what is missing here? maybe a particular perl module I can try to reinstall?

Thx a lot in advance

**Comment by BaldMansMojo** [comment]
Util::connect ist part of the VMware Perl SDK. SDK 5.x should be sufficiant. 6.x was buggy. 6.5 should work but not tested by me. Before testing the plugin test the SDK with the command line tools deliverd by VMware.
