### ISSUE TITLE
Working on Centos 7?

### ISSUE THREAD

**Issue by project707** [BaldMansMojo/check_vmware_esx#134]
I've seen the various references to this, and the issues with getting the CLI/SDK installed, but I have yet to find any instructions that work for Centos 7 all the way through to working monitoring.

Once by manually combining various input from other issues I've read, and once again by using the successful steps from this post https://morgajel.net/2015/05/20/1676 I have managed to install the SDK. I can run the plugin up to the point where I get the script timing out (no longer errors relating to missing libraries that I can see), but that's always the best i can do. I've gone through and made sure I have the right user (also created on the esxi server and granted admin role), permissions, removed the session files, etc., but I always end up with:
```
UNKNOWN: Script timed out.
```
I can verify that session and session_locked files are created

Like I mentioned I'm on Centos 7. I've also installed the 5.5 SDK per the instructions, and dealing with all of the errors that come up.

If you could direct me to some info that could help me get this working, I would be very appreciative.

**Comment by strfr** [comment]
On RHEL7 successful, had to remove the .pl extension to make it being executed by Icinga daemon, the long plugin replies solved thanks to this page [https://www.claudiokuenzler.com/blog/650/slow-vmware-perl-sdk-soap-request-error-libwww-version#.Wv01LmiFNaT](url)

**Comment by crapoulou** [comment]
Hello,

For info, I fought with this error and get it fixed.
The check was :
/usr/lib/nagios/plugins/check_vmware_esx.pl -H vcenter_IP_Address*.*.*.* -N vcenter_hostname -f /usr/lib/nagios/plugins/check_vmware_esx-master/authfile_vcenter.txt -S io -s read

On the vCenter, I just had to restart "**VMWare vAPI Endpoint**"

If that helps ;-)

**Comment by BaldMansMojo** [comment]
Works on CentOS7 and RHEL 7 with SDK 6.5 and above.. perl-libwww-perl-6.05-2.el7.noarch from ContOS 7.6 works fine.
