### ISSUE TITLE
Incorrect format of perf data in Net informations

### ISSUE THREAD

**Issue by interopbrasil** [BaldMansMojo/check_vmware_esx#136]
Greetings!
I've noticed that the net informations doesnt add semicolon to separate the value from the thresholds:

Line 3226
	$perfdata = "\'net_usage\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = "\'net_usage\'=" . $value .  ";" . $perf_thresholds . ";;";
Line 3232
	$perfdata = "\'net_usage\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = "\'net_usage\'=" . $value .  ";" . $perf_thresholds . ";;";

Line 3253: 
	$perfdata = $perfdata . " \'net_receive\'=" . $value . $perf_thresholds . ";;";	
	Should be: $perfdata = $perfdata . "\'net_receive\'=" . $value .  ";" . $perf_thresholds . ";;";
Line 3259
	$perfdata = "\'net_receive\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = "\'net_receive\'=" . $value .  ";" . $perf_thresholds . ";;";

Line 3289
	$perfdata = $perfdata . " \'net_send\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = $perfdata . " \'net_send\'=" . $value .  ";" . $perf_thresholds . ";;";
Line 3295
	$perfdata = "\'net_send\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = "\'net_send\'=" . $value .  ";" . $perf_thresholds . ";;";

Line 5771
	$perfdata = "\'net_usage\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = "\'net_usage\'=" . $value .  ";" . $perf_thresholds . ";;";
Line 5777
	$perfdata = "\'net_usage\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = "\'net_usage\'=" . $value .  ";" . $perf_thresholds . ";;";

Line 5798: 
	$perfdata = $perfdata . " \'net_receive\'=" . $value . $perf_thresholds . ";;";	
	Should be: $perfdata = $perfdata . "\'net_receive\'=" . $value .  ";" . $perf_thresholds . ";;";
Line 5804
	$perfdata = "\'net_receive\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = "\'net_receive\'=" . $value .  ";" . $perf_thresholds . ";;";

Line 5834
	$perfdata = $perfdata . " \'net_send\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = $perfdata . " \'net_send\'=" . $value .  ";" . $perf_thresholds . ";;";
Line 5840
	$perfdata = "\'net_send\'=" . $value . $perf_thresholds . ";;";
	Should be: $perfdata = "\'net_send\'=" . $value .  ";" . $perf_thresholds . ";;";

Thanks!

**Comment by BaldMansMojo** [comment]
Should be fixed. If not please reopen.
Martin
