### ISSUE TITLE
Check turned red after we decomissioned volumes, can't find how to turn it back green

### ISSUE THREAD

**Issue by Grimblee** [BaldMansMojo/check_vmware_esx#139]
Hello,

I believe most is in the title.

I'm checking a vcenter's volumes through your script and after decommissioning some volumes it turned red and I can't seems to find how to reset it.

Usually there would be data files in /tmp or something but I couldn't find them...

Could you tell me how I can turn it back to green ?

Message looks like this:
CRITICAL: 9 alert(s) found for some of the selected volume(s) (warn:90%, crit:95%)
Volumes above thresholds:
'FAS5_DS_K_H_SAS_PR_W_003_empty' is not accessible, 'FAS5_DS_K_H_SAS_PR_D_003_empty' is not accessible, 'FAS5_DS_K_H_SAS_PR_D_007_empty' is not accessible, 'FAS5_DS_K_H_SAS_PR_D_002_empty' is not accessible, 'FAS5_DS_K_H_SAS_PR_W_004_empty' is not accessible, 'FAS5_DS_K_H_SAS_PR_D_001_empty' is not accessible, 'FAS5_DS_K_H_SAS_PR_W_002_empty' is not accessible, 'FAS5_DS_K_H_SAS_PR_W_006_empty' is not accessible, 'FAS5_DS_K_H_SAS_PR_W_001_empty' is not accessible, ------------------------------------------------

Thank you,

**Comment by BaldMansMojo** [comment]
I know that problem. We had it here too. But that is not a fault of the plugin. The data is deliverd so from ESX. I know that we found the reason via Vcenter. But it was a long time ago and I don't know what it was.

Regards
Martin
