### ISSUE TITLE
Please add config option "--ok_in_maintenace_mode"

### ISSUE THREAD

**Issue by bb-Ricardo** [BaldMansMojo/check_vmware_esx#146]
Yep. That's right.And I merged it yesterday. But I will change it to "unknown" with next version because status is definitely not know when in maintenance mode.

_Originally posted by @BaldMansMojo in https://github.com/BaldMansMojo/check_vmware_esx/pull/145#issuecomment-495527112_

It would be great if maintenance mode would not return all checks as UNKNOWN to keep your monitoring environment cleaner. This way the admin can decide if he wants maintenance alerted.

also possible option "--maintenance_mode_state" with OK, WARNING, CRITICAL or UNKNWON.

Thanks

Cheers
Ricardo

**Comment by BaldMansMojo** [comment]
Yep. Will do it so.

**Comment by BaldMansMojo** [comment]
Done.
