### ISSUE TITLE
Host I/O statistics not pulled

### ISSUE THREAD

**Issue by lazyfrosch** [BaldMansMojo/check_vmware_esx#152]
Hi Martin,
I wondered why you changed `host_disk_io_info` and removed `$maintenance_mode_state`. (in e38697efd866655670d8ff1a4e5fa070e4a4e73f)

Now the API call is not correctly executed and no I/O values are returned.

Reverting those changes fixes the problem. Should I do a PR?

All Best
Markus

**Comment by BaldMansMojo** [comment]
Yep. Must be an error happening while resolving several merge conflicts. Was a lot of work merging all these requests and solving the issues. But the problem was that I had no SDK 6.x. And because the first request fixed some issues for SDK < Version 6.5 I couldn't merge them earlier.

Regards
Martin

**Comment by lazyfrosch** [comment]
I'll add this in my PR.

I will also address an issue with "unknowns" with newer ESXi releases, see https://kb.vmware.com/s/article/57171

**Comment by skupjoe** [comment]
Thanks for the IO fixes @lazyfrosch.

@BaldMansMojo please merge this PR at your earliest. We had an issue today and needed to track down IO latency, but, unfortunately, due to this API call not working Icinga wasn't collecting IO info during the event that transpired.

**Comment by BaldMansMojo** [comment]
Sorry - was 6 weeks ill at home not able to sit on my computer. The last 2 weeks at work was too much to do and now I'm 2 weeks at vacation. Will do it immediately when I'm back.

**Comment by mkayontour** [comment]
I works, thanks for the fix @lazyfrosch 
@BaldMansMojo enjoy your vacation :)
