### ISSUE TITLE
Server version unavailable at 'https://10.0.0.15:443/sdk/vimService.wsdl' at /usr/share/perl/5.26/VMware/VICommon.pm line 704

### ISSUE THREAD

**Issue by ThePizzaAvenger** [BaldMansMojo/check_vmware_esx#155]
@BaldMansMojo 
@Napsty 

Thanks to both of you for your contributions in the thread [https://github.com/BaldMansMojo/check_vmware_esx/issues/137](url).

I followed the link that Napsty provided [https://www.claudiokuenzler.com/blog/789/install-check_vmware_esx.pl-vmware-perl-sdk-6.7-ubuntu-xenial-icinga2](url) 

When I run `/usr/lib/vmware-vcli/apps/general/connect.pl --server 10.0.0.15` I get 

> Server version unavailable at 'https://10.0.0.15:443/sdk/vimService.wsdl' at /usr/share/perl/5.26/VMware/VICommon.pm line 704.

Running `vi +704 /usr/share/perl/5.26/VMware/VICommon.pm` shows 

`
      eval { $result = $xml_parser->parse_string($response->content) };
      if ($@) {
         die "Server version unavailable at '$url'";
      }`

- vSphere SDK for Perl version: 6.7.0
- Script 'vmware-cmd' version: 6.7.0
- Not using a proxy
- Using Ubuntu 18.04.2 LTS
- Not using any special characters in my password
- I'm able to ping by IP but that's obvious because I'm being prompted for credentials

I made this post in Source Forge [ https://sourceforge.net/p/veman/discussion/support/thread/6b0745979e/](url) but I just need to be patient for a response. Is there any info I can provide that would help with troubleshooting this issue?

I changed the /usr/share/perl/5.26/VMware/VICommon.pm file to have this line as per [https://communities.vmware.com/thread/240659?start=15&tstart=0](url):
`$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME}=0;` but my error is still the same.

Also reading [https://communities.vmware.com/thread/240659](url) I ran `/usr/share/perl/5.26/VMware$ sudo wget --no-check-certificate https://10.0.0.15/sdk/vimService.wsdl
--2019-06-29 23:23:43--  https://10.0.0.15/sdk/vimService.wsdl` and got the following back (but same results):

`Connecting to 10.0.0.15:443... connected.
WARNING: cannot verify 10.0.0.15's certificate, issued by ‘O=VMware Installer’:
  Unable to locally verify the issuer's authority.
    WARNING: certificate common name ‘localhost.localdomain’ doesn't match requested host name ‘10.0.0.15’.
HTTP request sent, awaiting response... 200 OK
Length: 545 [text/xml]
Saving to: ‘vimService.wsdl.1’

vimService.wsdl.1         100%[=====================================>]     545  --.-KB/s    in 0s      
2019-06-29 23:23:43 (27.6 MB/s) - ‘vimService.wsdl.1’ saved [545/545]`

**Comment by BaldMansMojo** [comment]
This was not an issue for the plugin. So I closed it.
