### ISSUE TITLE
setting warn/crit thresholds causes CRITICAL

### ISSUE THREAD

**Issue by fireheadman** [BaldMansMojo/check_vmware_esx#164]
Unsure why, but when I use the warn/crit thresholds in Icinga services, I end up with CRITICAL alerts...

![image](https://user-images.githubusercontent.com/19847195/70075270-a9324b00-15b9-11ea-93f5-51a1f667da35.png)

![image](https://user-images.githubusercontent.com/19847195/70075299-bcddb180-15b9-11ea-8652-c7c79e9ad884.png)

![image](https://user-images.githubusercontent.com/19847195/70075334-d1ba4500-15b9-11ea-90ca-23d5af383eca.png)

**Comment by BaldMansMojo** [comment]
Same procedure as every time. First test a plugin from the command line. If it worx - test it from the monitoring tool. So I do not use Icinga. Therefore I can't help for icinga2. So test it from the command line and I can help

**Comment by fireheadman** [comment]
for clarity, how would the CLI be tested using "vmware-esx-soap-host-io-read-latency" ?

**Comment by fireheadman** [comment]
found it....
Here ya go.

```
[user@icinga01 plugins ]$ sudo -u icinga ./check_vmware_esx -f /etc/icinga2/authfiles/esxi-auth --host virtprd70 --select io --subselect read_latency --warning 30 --critical 20
CRITICAL: I/O read latency=0 ms|'io_read_latency'=0ms;30;20;;
```

This is showing CRITICAL when the actual latency is "0ms".   This should be "OK"... right?

**Comment by BaldMansMojo** [comment]
Ok - this looks like a bug. I will have a look on it later this week,

**Comment by BaldMansMojo** [comment]
Ok - found one error (I think). UOM is ms. So threshold must also be given in ms. But this leads to another bug. I compare numerical values. But with ms it's a string compare. This could not work.  But this does not explain the second error. So I need more time.

**Comment by fireheadman** [comment]
no problem... glad to help test when you have a new release available.
