### ISSUE TITLE
Performance Data for UPTIME

### ISSUE THREAD

**Issue by teddyimsuff** [BaldMansMojo/check_vmware_esx#167]
It would be great to have performace data for "uptime" available, so you can check your history when and after what time a server has been restarted.

**Comment by BaldMansMojo** [comment]
First thing when I started with check_esx was to remove all things unnessecary for alerting. Uptime was one of them. For statistical issues use the tools from VCSA  or specialised stuff or whatever. To have a performance graph for uptime you only need a piece of paper, a pencil and a straithedge and draw a long increasing straight line. ;-))

**Comment by teddyimsuff** [comment]
> First thing when I started with check_esx was to remove all things unnessecary for alerting. 

I understand this totally! 

> so you can check your history when and after what time a server has been restarted

I wasn't talking about alerting, i was talking about history. When I am in Nagios i don't want to log into the VCSA just to check at what point an ESX host was restarted. VCSA is a slow piece of *** and I what to avoid it where ever i can.

Why not add an --perfdata option for the people who might want that information?

> To have a performance graph for uptime you only need a piece of paper, a pencil and a straithedge and draw a long increasing straight line

I really would like to see a picture of your monitor screens ;)

**Comment by BaldMansMojo** [comment]
Ok - so beside jokes. Several people where asking for an "uptime" check. But they wanted a "has my system had an unwanted restart" or something like that. That makes sense but can't be realized. Unfortunately. 

--perfdata. The information you wanna have is available with various (reporting) tools. Especially for this are quickstats in VMware available. This plugin is about alerting. Performancedata is more a "side effect". I talked with a lot of other specialists about such options. Most of them agree with me. No features collecting only data.

For your features I think tools like Grafana are better. I will definetely not implement it.
