### ISSUE TITLE
Check Centreon (No output returned from plugin)

### ISSUE THREAD

**Issue by Feliscucu** [BaldMansMojo/check_vmware_esx#170]
Hi, I need help.
The plugin is working from CLI but not from the Centreon Web Interface, which returns the error "No output returned from plugin"
From CLI:
./check_vmware_esx.pl -H 192.168.201.24 -f /usr/lib/centreon/plugins/esx.auth -S cpu -w 80 -c 90
Output: 
OK: CPU wait=1224038.00 ms - CPU ready=3317.00 ms - CPU usage=36.82%|'cpu_wait'=1224038.00ms;80;90;; 'cpu_ready'=3317.00ms;80;90;; 'cpu_usage'=36.82%;80;90;;

CENTREON:
I create new command with no $ARG$:
/usr/lib/centreon/plugins/check_vmware_esx.pl -H $HOSTADDRESS$ -f /usr/lib/centreon/plugins/esx.auth -S cpu -w 80 -c 90

but ...
![image](https://user-images.githubusercontent.com/63643185/81827681-4ca86400-9539-11ea-8fd9-45b62c873623.png)

![image](https://user-images.githubusercontent.com/63643185/81827852-75c8f480-9539-11ea-8a8a-099a1784b69d.png)

what am I doing wrong?
Thanks!

**Comment by BaldMansMojo** [comment]
If it's working from the command line the issue is caused by Centreon and not by the plugin- Typically you have problems with access rights. Test as the Centreon user.
