### ISSUE TITLE
Shows Vcenters gray but no errors in vCenter

### ISSUE THREAD

**Issue by 6485im43** [BaldMansMojo/check_vmware_esx#175]
Hi,

I'm getting the following result when testing the status of the vCenter
```
UNKNOWN: 0/1 Vcenters green - 0/1 Vcenters red - 0/1 Vcenters yellow - 1/1 Vcenters gray
RKU overall status=gray
```
with this command
` ./check_vmware_esx.pl -u svc_nagios -p password--datacenter=vcs01 -S runtime -s status`

The vCenter shows no errors.

The version of the vCenter and the SDK is 6.7.0. I also tested the SDK 5.5 and 6.5 which are described in your readme.
Does anyone know this error or it is happening because of the new vCenter update?

Thanks

**Comment by Beatlor** [comment]
The same for me. I have more than 50 VCenters all in status gray

UNKNOWN: 0/52 Vcenters green - 0/52 Vcenters red - 0/52 Vcenters yellow - 58/52 Vcenters gray
location1 overall status=gray
....

And a full list of all VCenters. I have only one VCenter Host running. How can I separate them for some checks?

**Comment by BaldMansMojo** [comment]
This is not a problem of the plugin. The call to the API gives back the status as it is deliverd by ESX. It's more a problem of your ESX installation. See module dc_runtime_info.pm for the code. Sorry.
