### ISSUE TITLE
Plugin shows health problem - Memory

### ISSUE THREAD

**Issue by gustavo-souto** [BaldMansMojo/check_vmware_esx#176]
Hi,

The output of -s health shows 1 health issues in memory:

`# ./check_vmware_esx.pl -D IP-VCENTER -C CLUSTER-VCENTER -u USER -p PASSWORD -S runtime -s health --cluster --failover -H SERVER-ESXI`

`WARNING: 1 health issue(s) found in 98 checks: 1) [Warning] [Type: Memory] [Name: Memory] [Label: Unknown] [Summary: All functionality is available but some might be degraded]`

But when I add -s listsensors, all the memory checks are Ok:

[Ok] [Type: Memory] [Name: Memory Device 1 B  12: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  12: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  11: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  11: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  10: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  10: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  9: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  9: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  8: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  8: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  7: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  7: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  6: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  6: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  5: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  5: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  4: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  4: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  3: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  3: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  2: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  2: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  1: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 B  1: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  12: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  12: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  11: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  11: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  10: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  10: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  9: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  9: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  8: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  8: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  7: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  7: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  6: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  6: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  5: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  5: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  4: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  4: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  3: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  3: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  2: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  2: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  1: Uncorrectable ECC - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]
[Ok] [Type: Memory] [Name: Memory Device 1 A  1: Correctable ECC logging limit reached - Deassert] [Label: Green] [Summary: Sensor is operating under normal conditions]

Does anyone know why the output shows issues?

Thanks.

**Comment by BaldMansMojo** [comment]
Sh.t. Was totally out of my scope. The cluster part was never finished. There should be a note about that.The cluster part was from old check_esx and mainly senseless. Especially the health check because it aggregated all nodes of a cluster. This makes partly sense for a resource group but not for a cluster. I have to take some time and finish it.

Sorry
