### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by aclark6996** [BaldMansMojo/check_vmware_esx#179]
Hello All,
I hope this message finds you all well.  First, I want to say THANK YOU for the great VMware plugin. We are using this with Icinga2 to monitoring all our VM Host and Virtual Machine that we are not allowed to install the Icinga agent on.  It is working great and I do not have a problem currently with the plugin, but I have some enhancement requests if possible.  I would love to help and improve the plugin, but I do not have any experience with Perl programing ☹.  By the time I learn programing in Perl you probably could have these request completed.
Here is a list of suggested enhancement if possible.

1.	**Host Uptime Threshold** – could a time threshold get added to the uptime check to send a problem alert out if the threshold is reached?  (Example: A warning alert is sent out if a Host is up for 365 days)
_check_vmware_esx -D myDataCenter -H myHost  -S uptime -w 365d -c 730d_
2.	**Host Uptime Negative Threshold** – could a negative time threshold get added to the uptime check to send a problem alert out if the uptime is less than the threshold.  (Example: A host is restarted the uptime would be less than 30 minutes)
_check_vmware_esx -D myDataCenter -H myHost  -S uptime -w -30m_
3.	**Virtual Machine Uptime** – Currently the uptime check for virtual machines is not possible.  Could an uptime check get added for Virtual Machines?
_check_vmware_esx -D myDataCenter -N myVM  -S uptime_
  a.	**VM Uptime Threshold** – same as first request on Host but used on VM
  _check_vmware_esx -D myDataCenter -N myVM  -S uptime -w 90d -c 180d_
  b.	**VM Uptime Negative Threshold** – same as second request on Host but used on VM
  _check_vmware_esx -D myDataCenter -N myVM  -S uptime -w -30m_ 
4.	**Virtual Machine Disk Check** – could you add a check for the usage of a disk on a VM? (Example:  C: drive size on virtual windows server) 
_check_vmware_esx -D myDataCenter -N myVM  -S volumes -s C:\ -w 80% -c 90%_ 
Currently you have a volume check for Host, maybe this new check could be like the volume check for Host except for VM including thresholds.  
5.	**Virtual Machine Powerstate Threshold** – could a threshold get added to the runtime state of a VM?  Currently if you use the runtime powerstate and the VM is poweredoff the monitoring check always says “OK” but monitoring output message says “poweredoff”.  If would be nice to have a threshold change when the VM is poweredoff.
_check_vmware_esx -D myDataCenter -N myVM  -S runtime -s powerstate -w suspended -c poweredOff_ 

Sorry my list kepts getting longer as I wrote it out.  If you have any question for me, please let me know (donald.clark@sunchemical.com).  I would love to help if I could.  Maybe I could help test a beta version if needed.  Thanks again for all your hard work.

Regards 
Alex

**Comment by BaldMansMojo** [comment]
1-2) Doesn't makes sense to most of us - so no.
3) Check the VM like any other (physical) server. So there is no need to implement it.
4) Same as 3)
5) Doesn't makes sense to most of us. If you set a threshold in monitoring and admin takes guest down for a couple of days you will probably cause misalerts. And you can check it directly from monitoring. I use Naemon. So with the macro $LASTHOSTDOWN$ you can see in epoch when host last went down. Pass it to a shell script as plugin and you have your check
