### ISSUE TITLE
Plug in for vSphere 6.7

### ISSUE THREAD

**Issue by fasilcv86** [BaldMansMojo/check_vmware_esx#183]
I have VMware vSphere 6.7 and Nagios core 4 on RHEL7

Installed VMware SDK 6.7 on Nagios sever and connection is success thru SDK connect. 

Which tool I can used for monitoring this. Can I get the steps if any additional.

**Comment by mskaraca** [comment]
in the nagios server part: install dependencies and copy the plugin (to the libexec dir)
in the vmware vcenter/esxi hots: create a read only user (e.g. nagios)
open port 443 between vmware vcenter/esxi host and nagios server (if a firewall exists..)

now use plugin in the command line to collect data.. example:
/usr/local/nagios/libexec/check_vmware_esx  -H esxi_IP -f esxi_auth.txt  --select=runtime

esxi_auth.txt must include
username=nagios
password=secret_password

read the manual for more..
