### ISSUE TITLE
Script timed out

### ISSUE THREAD

**Issue by LDorian** [BaldMansMojo/check_vmware_esx#185]
Hello all, @BaldMansMojo 

I followed the install process, everything was working perfectly but after few minutes several checks are on "UNKNOWN : Script timed out". 
Currently I'm running on Perl SDK 6.7. I also tried to run on SDK 5.5 and same issue.
I tried to downgrade libwww-perl but without success.
Is anything else I could do to solve this issue ?
Dorian

**Comment by BaldMansMojo** [comment]
If it's working and afterwords got a timeout it has normally nothing to do with the plugin. Have you tested from command line?
Martin
