### ISSUE TITLE
vmware 6.7 sdk question

### ISSUE THREAD

**Issue by mvrgotiks** [BaldMansMojo/check_vmware_esx#187]
Hi all, 
This issue might not be related to SDK, but I would like to verify with you.
I have an Icinga master-satellite setup and I am having troubles getting check_vmware_esx to work via Icinga.

The check should be reading out health status from VMWare 6.5 cluster setup, managed by vcenter instance.

I am running check_vmware_esx from satellite node are working perfectly:

***as Root user**

```
[root@icinga2-hilversum-satellite-1 ~]# '/usr/lib64/nagios/plugins/check_vmware_esx' '--authfile' '/etc/icinga2/authfiles/nl-vcenter-auth' '--datacenter' 'vcenter.avinity.tv' '--select' 'runtime' '--sessionfiledir' '/var/spool/icinga2/tmp' '--sslport' '443' '--subselect' 'listhost' '--timeout' '90'
OK: 3/3 Hosts powered on - 0/3 Hosts powered off/standby/unknown
esxi6-jira.avinity.tv(poweredOn)
esxi6-myla.avinity.tv(poweredOn)
esxi6-ops.avinity.tv(poweredOn)
```

```
[root@icinga2-hilversum-satellite-1 ~]# '/usr/lib64/nagios/plugins/check_vmware_esx' '--authfile' '/etc/icinga2/authfiles/nl-vcenter-auth' '--datacenter' 'vcenter.avinity.tv' '--select' 'runtime' '--sessionfiledir' '/var/spool/icinga2/tmp' '--sslport' '443' '--subselect' 'listcluster' '--timeout' '90'
OK: 2/2 Clusters green - 0/2 Clusters red - 0/2 Clusters yellow - 0/2 Clusters gray
HV HA Cluster (green)
Hilversum HA Cluster (green)
```

***as Icinga user**

[root@icinga2-hilversum-satellite-1 ~]# sudo -u icinga '/usr/lib64/nagios/plugins/check_vmware_esx' '--authfile' '/etc/icinga2/authfiles/nl-vcenter-auth' '--datacenter' 'vcenter.avinity.tv' '--select' 'runtime' '--sessionfiledir' '/var/spool/icinga2/tmp' '--sslport' '443' '--subselect' 'listcluster' '--timeout' '90'
OK: 2/2 Clusters green - 0/2 Clusters red - 0/2 Clusters yellow - 0/2 Clusters gray
HV HA Cluster (green)
Hilversum HA Cluster (green)

**This should mean that all Perl modules, lib pointers, and VMWare modules work fine** ??

However, in Icinga Web UI I see the following error and the same error for all check_vmware_esx checks:

` Server version unavailable at ‘https://vcenter.avinity.tv:443/sdk/vimService.wsdl’ at /usr/share/perl5/VMware/VICommon.pm line 704.`

**Comment by BaldMansMojo** [comment]
If it runs from commandline everything is ok. If it doesn't work from your monitoring systems (I use Naemon) you normally have a problem with access rights.

**Comment by mvrgotiks** [comment]
My apologies for such delay in response. You were absolutely right. I did not catch it right away but the problem was in the SELinux flag set on the system's executable. Apparently, I was using the command module which was "resetting" the SELinux flag with every run, but I did not see it right away.
Thank you - it all works now.
