### ISSUE TITLE
Basic host check (select=soap) says error but returns "OK"-state

### ISSUE THREAD

**Issue by CHOOH1992** [BaldMansMojo/check_vmware_esx#189]
Hi,
started checking to base connection to my esxi host before running multiple checks on them. Randomly I noticed that if the user login via SOAP fails (for example by wrong credentials) the check does not result in critical/warning/unknown state. Could you check this and may fix? :-)
`./check_vmware_esx --user monitoring --password "YouWontGetIT" --datacenter 10.123.123.123 --select=soap`
Best regards

**Comment by BaldMansMojo** [comment]
Unfortunately not. It's caused by SDK.
