### ISSUE TITLE
Switch SDK Timeout to Critial

### ISSUE THREAD

**Issue by nmeyer00** [BaldMansMojo/check_vmware_esx#193]
Hi there,

I have a suggestion regarding the exit code for SDK errors.

A warning is currently set if the sdk runs on a timeout. Wouldn't it be better to set all SDK errors to Critical or Unknown?

**Comment by BaldMansMojo** [comment]
Well - in the past it was critcal which lead to complaints. I'll make it user configurable in next version. I let this issue open to not forget it.

**Comment by nmeyer00** [comment]
Thanks 👍
