### ISSUE TITLE
Status UNKNOWN - 169 health issue(s) found in 289 checks:

### ISSUE THREAD

**Issue by ShowMeYourSkil** [BaldMansMojo/check_vmware_esx#197]
Hi,

I get several errors when querying the ESX health that the physical elements can not be queried, which I can not explain. 
Can anyone help me? I have copied you the entire error in a pastebin file.

https://pastebin.com/81g9NhmZ

Best regards

**Comment by BaldMansMojo** [comment]
This is caused by your hardware / ESX installation. To get it work in ESX manufactures often delivers extra drivers/utilities. So often ESX ses the sensors but can't access the data without additional drivers. This can't be fixed. You can suppress it by using option --ignore_unknown
