### ISSUE TITLE
check_vmware_esx and pnp4nagios compatibility

### ISSUE THREAD

**Issue by iovcho** [BaldMansMojo/check_vmware_esx#200]
Hello. How can I use check_vmware_esx with pnp4nagios graphics compatibility?
Thanks!

**Comment by BaldMansMojo** [comment]
I use it from the beginning. Performance data is standard.

**Comment by iovcho** [comment]
Dear @BaldMansMojo , thank you very much for your fast reply.
I installed the plugin, but pnp4nagios is empty. Can you provide me some information how can I debug what is the problem?
Here is the output:

[root@nagios ~]# /opt/check_vmware_esx/check_vmware_esx.pl -H 11.22.33.44 -f /root/.testpass -S net

OK: net usage=1409.00 KBps net receive=648.00 KBps, net send=761.00 KBps NICs total:4 NICs attached to switch:1 NICs connected:1 NICs disconnected:0 NICs ignored:0|'net_usage'=1442816B;;;; 'net_receive'=663552B;;;; 'net_send'=779264B;;;;



But the graphs are empty:

![image](https://user-images.githubusercontent.com/11993248/186649563-52ca1394-4c24-4604-8f9e-ec8d34b8c8c0.png)

Some pnp4nagios template is missing or? Thank you very much again for yours help!

**Comment by iovcho** [comment]
For other services like a ping, CPU load, etc pnp4nagios working correctly.

**Comment by BaldMansMojo** [comment]
As you see performance date are delivered (all after the |) and RRD Files are created. So wait a while. If there are no graphs after a while check your monitor system configuration. The plugin works correctly.
