### ISSUE TITLE
Can't locate Time/Duration.pm in @INC

### ISSUE THREAD

**Issue by Arkarlos** [BaldMansMojo/check_vmware_esx#205]
Hi Master, I have this error with the Check:

(No output on stdout) stderr: Can't locate Time/Duration.pm in @INC (@INC contains: /usr/lib64/perl5/libwww-perl-5.837/lib /usr/lib64/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/share/perl5 .) at /usr/local/nagios/libexec/check_vmware_esx line 8791.
BEGIN failed--compilation aborted at /usr/local/nagios/libexec/check_vmware_esx line 8791.

Can you help me?

**Comment by BaldMansMojo** [comment]
Install the perl module perl-Time-Duration. Depending on your OS it's a .deb or a .rpm package. Prefer the package instead of installing it manually from CPAN. This issue has nothing to do with the plugin
