### ISSUE TITLE
Non existent cluster name cause script error

### ISSUE THREAD

**Issue by ccesario** [BaldMansMojo/check_vmware_esx#44]
When passed a non existent cluster as param, the script return a script error

/tmp/check_vmware_esx/check_vmware_esx --authfile /tmp/check_vmware_esx/auth --datacenter 192.168.X.X --cluster **WrongName** --sessionfile check-vmware-esx.session --sessionfiledir /tmp --timeout 90 -S runtime
`Can't use string ("WrongName") as a HASH ref while "strict refs" in use at /tmp/check_vmware_esx/check_vmware_esx line 8780.`

/tmp/check_vmware_esx/check_vmware_esx --authfile /tmp/check_vmware_esx/auth --datacenter 192.168.X.X --cluster **Cluster** --sessionfile check-vmware-esx.session --sessionfiledir /tmp --timeout 90 -S runtime
`18/24 VMs up, overall status=green, no config issues|vmcount=18;;;;`

**Comment by BaldMansMojo** [comment]
Sorry - cluster is old stuff from op5 and buggy. But I had not the time for a real clean up. But it is on my to do list.
