### ISSUE TITLE
check volumes not showing correctly in nagios webinterface

### ISSUE THREAD

**Issue by reneubert** [BaldMansMojo/check_vmware_esx#49]
Hello,

first of all many thanks for the great plugin...
I got it running but unfortunately the "volumes" check isn't running 100% correct.

If I'm running the command (/usr/bin/perl ./check_vmware_esx.pl -f /usr/local/nagios/libexec/check_vmware_esx.txt -H x.x.x.x -S volumes --gigabyte -w 20% -c 10% --exclude local_xxx)
n the commandline I get the correct result. (a few volumes aboive and below the thresholds)

In the Nagios webinterface all it shows is: 

OK for selected volume(s).
Volumes above thresholds:
------------------------------------------------
Volumes below thresholds:

My nagios commands looks like this:

commands.cfg:
define command{
	command_name	check_esx_datastores
	command_line	/usr/bin/perl $USER1$/check_vmware_esx.pl -f /usr/local/nagios/libexec/check_vmware_esx.txt -H $HOSTADDRESS$ -S $ARG1$ --gigabyte -w $ARG2$ -c $ARG3$ --exclude local_esxk01
	}
	
host.cfg

define service{
			use                             generic-service-60m         
			host_name		   xxxx
			service_description     __Disk Usage
			check_command	    check_vmware_esx!volumes!20%!10%
			}
		

I dunno if that's an error or I just did a mistake. But I would appreciate if you could point me to the right direction :)

Thanks in advance.

Best regards,
Rene

**Comment by BaldMansMojo** [comment]
Hi,

it's a multiline output. That means (in classical nagios) you will only have line 1 displayed in overview and have to look at the detailed view. This may be ok if you use Thruk as interface because you have a popup windows with the details. If you wanna have all in the overview add --multiline which mixes some HTML tags (<br>) into the output. But beware to filter these tags out before sending emails, SMS or whatever. A sample for this in in the readme and in the inline docs.

Please give a feedback if it works so I can close the issue.

Best regards
Martin

**Comment by reneubert** [comment]
Hi Martin,

wow, that was fast :)

Unfortunately I don't see any  information about my volumes in the detailed view...
It just shows:

![19-01-2015 13-58-35](https://cloud.githubusercontent.com/assets/10597800/5800776/4427bc5a-9fe3-11e4-86f2-94e2b4c53616.png)

Best regards,
René

**Comment by BaldMansMojo** [comment]
I need the output from the commandline test.
Best regards
martin

**Comment by reneubert** [comment]
Critical! 4 alert(s) found for some of the selected volume(s) (warn:20%,crit:10%)
Volumes above thresholds:
XXX_HSM01 (VMFS) free: 22.78 GB (1.11%) / 2047.75 GB (100%)
XXX_VOL7 (VMFS) free: 150.73 GB (7.36%) / 2047.75 GB (100%)
XXX_VOL2 (VMFS) free: 355.13 GB (17.34%) / 2047.75 GB (100%)
XXX_VOL1 (VMFS) free: 312.37 GB (15.25%) / 2047.75 GB (100%)
------------------------------------------------
Volumes below thresholds:
XXX_VOL3 (VMFS) free: 509.05 GB (24.86%) / 2047.75 GB (100%)
XXX_VOL4 (VMFS) free: 542.38 GB (26.49%) / 2047.75 GB (100%)
XXX_VOL8 (VMFS) free: 518.58 GB (25.32%) / 2047.75 GB (100%)
XXX_VOL9 (VMFS) free: 1185.47 GB (57.89%) / 2047.75 GB (100%)
XXX_VOL6 (VMFS) free: 920.52 GB (44.95%) / 2047.75 GB (100%)
XXX_VOL5 (VMFS) free: 609.68 GB (29.77%) / 2047.75 GB (100%)|'XXX_VOL3'=509.05GB;409.55;204.77;;2047.75 'XXX_VOL4'=542.38GB;409.55;204.77;;2047.75 'XXX_VOL8'=518.58GB;409.55;204.77;;2047.75 'XXX_HSM01'=22.78GB;409.55;204.77;;2047.75 'XXX_VOL9'=1185.47GB;409.55;204.77;;2047.75 'XXX_VOL7'=150.73GB;409.55;204.77;;2047.75 'XXX_VOL6'=920.52GB;409.55;204.77;;2047.75 'XXX_VOL5'=609.68GB;409.55;204.77;;2047.75 'XXX_VOL2'=355.13GB;409.55;204.77;;2047.75 'XXX_VOL1'=312.37GB;409.55;204.77;;2047.75


Best regards,
René

**Comment by BaldMansMojo** [comment]
Send me please some screenshots to mf@maerber.de:
- Nagios status overview
- Detailed view nagios
- Commandline (copy & paste in GitHub has some nice side effects)
- Tail from your logfile (so retrigger the check from nagios and make a screenshot from the logfile.
Best regards
Martin
