### ISSUE TITLE
Information about peripherals with threshold!

### ISSUE THREAD

**Issue by pochand** [BaldMansMojo/check_vmware_esx#51]
Hi,
after define command and service in Nagios in this way:

define command{
command_name cpu_esxi_disk
command_line $USER1$/check_vmware_esx.pl -H $HOSTADDRESS$ -u $USER10$ -p $USER11$ -s $ARG1$ -s $ARG5$ -N $ARG4$ -w $ARG2$ -c $ARG3$
}

define service{
use vmware-service
host_name srv-voip
service_description disk
check_command cpu_esxi_disk!volumes!80!90
}

on web-interface it show only that service is OK and that the used space is under threshold but without show me the used space and the total space.
It is normal or I wrong some configuration??

![schermata da 2015-02-23 12 09 48](https://cloud.githubusercontent.com/assets/11058994/6326913/dea8676e-bb56-11e4-9eac-85408079b0c7.png)
![schermata da 2015-02-23 12 09 56](https://cloud.githubusercontent.com/assets/11058994/6326915/e57506ba-bb56-11e4-9bef-83d1ddc3a95c.png)

It is possible to have all information about volumes && the threshold??
Regards
GD

**Comment by BaldMansMojo** [comment]
Hi,

output is ok because it is a multiline output. If you use Thruk as WebGui you can point with your mouse ove the message an will see all in a popup. If you will see all in standard interface use --multiline but prepare your notification commands to filter out the HTML code. It's described in the readme file.

Regards
Martin

**Comment by pochand** [comment]
I tried to change something but at the end of all, the output is this:

![schermata da 2015-02-23 16 14 53](https://cloud.githubusercontent.com/assets/11058994/6330311/5c898206-bb77-11e4-9690-07a46326f1fa.png)

How I can see the really multiline output??

**Comment by BaldMansMojo** [comment]
cg.cfg:
escape_html_tags=0
Otherwise HTML will be escaped.
Martin

**Comment by pochand** [comment]
OOOOH :D :D :D 
Thank you very much !
Giuseppe
