### ISSUE TITLE
Possibility to have IOPS for ESX host or vm ?

### ISSUE THREAD

**Issue by LeDistordu** [BaldMansMojo/check_vmware_esx#55]
I just found I/O rate (io usage) but not IOPS ? It's possible or it's feature demand ? :)

**Comment by BaldMansMojo** [comment]
Do you mean I/O per second? If yes I have to look into the perf counters. Basically I first cleaned up the old plugin vom OP5. They used a log of ESX 4 perf counters. I cleaned it all up and replaced is with the stuff from ESX 5. But adding new things was/is the next big thing on my to do list. But some smaller things are added.

**Comment by LeDistordu** [comment]
Yes I/O per second for vm or host :) So it's feature ;)

**Comment by BaldMansMojo** [comment]
Although I have posted 2 new versions this is still not implemented and currently I'm short of time (annual tax declaration, pubescent kids, a wife ..... and a stressing fulltime job(but I need the money ;-) )).
But I will do it as soon as possible. But first I have to test the plugin with SDK 6.x

Best regards
Martin

**Comment by LeDistordu** [comment]
no problem ;)

thank you for your work ;)

**Comment by DeltaLima** [comment]
It seems that you accidently have copied some changelog stuff to line 1380-1384.

**Comment by BaldMansMojo** [comment]
Fixed. Happened after testing. Thanks for the hint.

Regards - Martin

**Comment by LeDistordu** [comment]
Something new ? I launch my infrastructure in a month and I wish I had a return on I/O.

Thank for your work ;)

**Comment by BaldMansMojo** [comment]
Sorry - not possible.
