### ISSUE TITLE
Required trailing slash for $plugin_cache

### ISSUE THREAD

**Issue by haukebruno** [BaldMansMojo/check_vmware_esx#56]
A trailing slash is required when setting *$plugin_cache*. Without the trailing slash, line 1639 will fail while executing the check.

It would be cool, if you can add a "trailing slash check" like in line 1633-1635 for *$sessionfile_name*.

**Comment by BaldMansMojo** [comment]
This is the default as deliverd:

my  $plugin_cache="/var/nagios_plugin_cache/"; # Directory for caching plaugin data. Good idea to use a tmpfs
You see there is a trailing slash. Perhaps you have deleted when you customized it. No one else had this problem.

Sorry - Martin
