### ISSUE TITLE
redundant thresholds in perfdata output

### ISSUE THREAD

**Issue by simonmeggle** [BaldMansMojo/check_vmware_esx#58]
Hi Martin, 
I think that the thresholds e.g. for CPU usage should only be present at the ``cpu_usage`` label (which is % and what I wanted to monitor), but not for ready and wait time (which is ms). 

    CPU wait=59782.00 ms - CPU ready=11.00 ms - CPU usage=0.46% |
    'cpu_wait'=59782.00ms;80;90;; 'cpu_ready'=11.00ms;80;90;; 'cpu_usage'=0.46%;80;90;;

Should be

    CPU wait=59782.00 ms - CPU ready=11.00 ms - CPU usage=0.46% |
    'cpu_wait'=59782.00ms;;;; 'cpu_ready'=11.00ms;;;; 'cpu_usage'=0.46%;80;90;;

**Comment by BaldMansMojo** [comment]
Fixed by a patch of you. ;-)))
Regard, Martin
