### ISSUE TITLE
Usage of sessionfile 

### ISSUE THREAD

**Issue by simonmeggle** [BaldMansMojo/check_vmware_esx#59]
Hi Martin, 

just curios... how can a sessionfile be used in production when it expires after 30 minutes? 
=> What happens if I pause all monitoring checks for 60 minutes? 

Regards, Simon

**Comment by BaldMansMojo** [comment]
Nothing happens. The plugin determines that there is no valid session and logs in with user and password. From this moment on you have a new valid session(file). A side effect of this is if you have a corrupted session file (which happened rarely in the past) you only have to remove the session file. Next try you have a new valid session.

Regards, Martin
