### ISSUE TITLE
NIC whitelisting 

### ISSUE THREAD

**Issue by simonmeggle** [BaldMansMojo/check_vmware_esx#61]
ist not available, only blacklisting. 
Perhaps someone has the need to whitelist NICs....

**Comment by BaldMansMojo** [comment]
This didn't happen in the past. And no one ask for whitelisting here before. 

Normally you have a bunch of NICs but only some you don't wont to see. I think white listing here can cause some problems. Think of a replacement NIC. The Vmware admin takes care of replacing the NIC but it is not the same (brand, model or so) and he forgets to tell the monitor admin about the change. So you will think that everything is ok but it isn't. You wont' see the new NIC. And often admins only look on the monitor in case they got an email or recocgnize a problem. Therefore I think whitelisting is obsolete here. 

Regards, Martin
