### ISSUE TITLE
Multiple checks broken with recent checkin.

### ISSUE THREAD

**Issue by morgajel** [BaldMansMojo/check_vmware_esx#64]
This showed up with the latest pull. When an actual issue pops up, the script fails and produces an unknown status. Here's the stacktrace:

```
Scalar found where operator expected at /opt/check_vmware_esx/modules//dc_runtime_info.pm line 520, near "$state"
	(Missing semicolon on previous line?)
syntax error at /opt/check_vmware_esx/modules//dc_runtime_info.pm line 519, near "]"
syntax error at /opt/check_vmware_esx/modules//dc_runtime_info.pm line 799, at EOF
Compilation failed in require at /opt/check_vmware_esx/check_vmware_esx.pl line 2154.
```

I get this stacktrace for the following checks:
* runtime listhost 
* runtime issue
* runtime listcluster
* runtime status

**Comment by BaldMansMojo** [comment]
Fixed. Reason? Old eyes in the middle of the night. Typed in a square backet instead of a curly one. And due to the fact that I was on vacation and at home it was not tested so good as normally. Sorry. Should work now.

Martin

**Comment by morgajel** [comment]
confirmed fixed.
