### ISSUE TITLE
Option --open-vm-tools for vm_runtime_info 

### ISSUE THREAD

**Issue by lbetz** [BaldMansMojo/check_vmware_esx#65]
Hi Martin,

I'd like to use the new option --open-vm-tools for vm too. Maybe the following would work.

Bye Lennart

diff --git a/modules/vm_runtime_info.pm b/modules/vm_runtime_info.pm
index 56c6682..5d129be 100644
--- a/modules/vm_runtime_info.pm
+++ b/modules/vm_runtime_info.pm
@@ -262,7 +262,14 @@ sub vm_runtime_info
                    if ($vm_view->guest->toolsVersionStatus eq "guestToolsUnmanaged")
                       {
                       $tools_out = "VMware Tools are installed and running, but not managed by VMWare. ";
-                      $actual_state = 2;
-                         if (defined($openvmtools))
-                         {
-                         $actual_state = 0;
-                         }
-                         else
-                         {
-                         $actual_state = 2;
-                         }
                     }
                  }
               else

**Comment by BaldMansMojo** [comment]
Hi Lennart,

please explain. I'm to stupid to understand :-))

Martin

**Comment by lbetz** [comment]
You implemented the the new option --open-vm-tools for dc_runtime_info(), that's fine. I'm missing it in vm_runtime_info() to request a dedicate vm.

**Comment by BaldMansMojo** [comment]
Hi Lennart,
after a long time I spent a lot work these days. This is fixed now. See latest version. Merged nearly all pull requests and some other changes.

Bis zum Herbst.
Martin

**Comment by lbetz** [comment]
thx.
