### ISSUE TITLE
check runs only under uid root

### ISSUE THREAD

**Issue by baramann** [BaldMansMojo/check_vmware_esx#68]
Hello,

when I run the script on the command line under root, everything is fine, when i user another uid, the scripts stops after some minutes, i get this error

OMD[tf]:~/local/lib/nagios/plugins$ ./check_vmware_esx.pl -D vcenter01 -H esxi01 -S mem -f ./blub
SOAP request error - possibly a protocol issue: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<RetrievePropertiesResponse xmlns="urn:vim25"><returnval><obj type="HostSystem">host-105</obj><propSet><name>name</name><val xsi:type="xsd:string">esxi04.boskg.local</val></propSet></returnval><returnval><obj type="HostSystem">host-139</obj><propSet><name>name</name><val xsi:type="xsd:string">esxi06.boskg.local</val></propSet></returnval><returnval><obj type="HostSystem">host-184</obj><propSet><name>name</name><val xsi:type="xsd:string">esxi05.boskg.local</val></propSet></returnval><returnval><obj type="HostSystem">host-210</obj><propSet><name>name</name><val xs
^CUNKNOWN: Script killed by monitor.
OMD[tf]:~/local/lib/nagios/plugins$ ll

MD[tf]:~/local/lib/nagios/plugins$ perl -v
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
Copyright 1987-2009, Larry Wall

[root@vtf-monitor anchors]# esxcli --version
Script 'esxcli' version: 6.0.0

Thanks

**Comment by BaldMansMojo** [comment]
Do you use SDK version 6? There are several errors with version 6. (See other issues). Currently all 5.x are tested. According to the docs I read SDK 5.x should also work for Vsphere 6.x exept some new features. But as ong as the plugin doesn't use it... .
See https://github.com/BaldMansMojo/check_vmware_esx/issues/52 . Looks like the same error. At this time I'm setting up my new nagios machines. I will try SDK 6.

**Comment by baramann** [comment]
so, i downgrade to 5.5, but i have still the same isse:

[root@vtf-monitor plugins]# ./check_vmware_esx.pl -H 1.1.1.1 -f ./authfile -S mem
OK: mem usage=34.55% - consumed memory=45276.82 MB - swap used=2601.44 MB - overhead=0.00 MB - memctl=15367.73 MB: |'mem_usage'=34.55%;;;; 'consumed_memory'=45276.82MB;;;; 'mem_swap'=2601.44MB;;;; 'mem_overhead'=0.00MB;;;; 'mem_memctl'=15367.73MB;;;;
[root@vtf-monitor plugins]# su - tf
OMD[tf]:~$ cd /omd/sites/tf/local/lib/nagios/plugins
OMD[tf]:~/local/lib/nagios/plugins$ ./check_vmware_esx.pl -H 1.1.1 -f ./authfile -S mem


Connecet via esxcli works fine


OMD[tf]:~$ esxcli -s esxi02 vm process list
Enter username: root
Enter password:
vtf-monitor
   World ID: 36712
   Process ID: 0
   VMX Cartel ID: 36711
...

OMD[tf]:~/local/lib/nagios/plugins$ ./check_vmware_esx.pl -H 10.211.0.12 -f ./authfile -S mem
SOAP request error - possibly a protocol issue: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<RetrievePropertiesResponse xmlns="urn:vim25"><returnval><obj type="PerformanceManager">ha-perfmgr</obj><propSet><name>perfCounter</name><val xsi:type="Arra                                                      yOfPerfCounterInfo"><PerfCounterInfo xsi:type="PerfCounterInfo"><key>0</key><nameInfo><label>Usage</label><summary>CPU usage as a percentage during the inte                                                      rval</summary><key>usage</key></nameInfo><groupInfo><label>CPU</label><summary>CPU</summary><key>cpu</key></groupInfo><unitInfo><label>%</label><summary>Per                                                      centage</summary><key>percent</key></unitInfo><rollupType>none</rollupType><statsType>rate</statsType><associatedCounterId>1</associatedCounterId><associate

**Comment by BaldMansMojo** [comment]
I think you have a problem with the authfile. First try it with user and password. If this works for both check the rights. Several people had trouble with auth files. Mostly it were access rights, DOS format of the file (Perl doesn't like it) etc. I myself don't use it. I have the userid and passwords in the service check defintions. This has the benefint to have one command defintion usable for ESX hosts with different users.

**Comment by baramann** [comment]
i do some more testing. 
my system is OMD with thruk. The user under which omd is running, have a 

export PERL5LIB="$OMD_ROOT/local/lib/perl5/lib/perl5:$OMD_ROOT/lib/perl5/lib/perl5:$PERL5LIB"

configured, without this PERL5LIB var, the check_vmware_esx.pl works also under my monitoring account, but without this var, omd/thruk does not work anymore :-(

is there a way to change the lib order in your check_vmware_esx.pl script or do you have another idea?

Thanks
Bjoern

**Comment by BaldMansMojo** [comment]
Okay. OMD is somewhat special. A friend of mine working as a consultant here in Germany has written an article for a magazine. But it is in german. Where have you installed my plugin?

**Comment by baramann** [comment]
it installed under /omd/sites/tf/local/lib/nagios/plugins
perhaps it is possible to start your program via an wraper.sh where i can unset PERL5LIB?

**Comment by BaldMansMojo** [comment]
Well - no one had this problem in the past. And a lot of users are using OMD. Send me a mail please. My email ist available with my personal data. From where do you write?

**Comment by baramann** [comment]
my workaround. a wrapper script:

#!/bin/bash
unset PERL5LIB
/omd/sites/tf/local/lib/nagios/plugins/check_vmware_esx.pl "$@"
BACK=$?
exit $BACK
