### ISSUE TITLE
Network statistics

### ISSUE THREAD

**Issue by ywauthy** [BaldMansMojo/check_vmware_esx#69]
Hey,

It seems that the network statistics are not correctly reported.

For example : 

Values from vcenter :

Counter: Usage
Instance :
Description: Network utilization (combined transmit-rates and receive-rates) during the interval
Units: KBps
Sample info : 20,2015-06-19T09:42:00Z
Value: 35195

Counter: Data receive rate
Instance :
Description: Average rate at which data was received during the interval
Units: KBps
Sample info : 20,2015-06-19T09:42:00Z
Value: 34983

Counter: Data transmit rate
Instance :
Description: Average rate at which data was transmitted during the interval
Units: KBps
Sample info : 20,2015-06-19T09:42:00Z
Value: 211

plugin output :
OK: net usage=35195.00 KBps, net receive=34983.00 KBps, net send=34982.00 KBps|'net_usage'=35195.00;;;; 'net_receive'=34983.00;;;; 'net_send'=34982.00;;;;

I have search a little bit and see that it's not always the same nic that is checked : 

$VAR1 = bless( {
                 'value' => '35195',
                 'id' => bless( {
                                  'counterId' => '143',
                                  'instance' => ''
                                }, 'PerfMetricId' )
               }, 'PerfMetricSeriesCSV' );

$VAR2 = bless( {
                 'value' => '34983',
                 'id' => bless( {
                                  'counterId' => '148',
                                  'instance' => ''
                                }, 'PerfMetricId' )
               }, 'PerfMetricSeriesCSV' );

$VAR3 = bless( {
                 'value' => '34982',
                 'id' => bless( {
                                  'counterId' => '149',
                                  'instance' => 'vmnic1'
                                }, 'PerfMetricId' )
               }, 'PerfMetricSeriesCSV' );

Because of this line :
$values = return_host_vmware_performance_values($vmname, 'net', ('usage.average:', 'received.average:_', 'transmitted.average:_'));

It only keep the value of the last nic corresponding to this counter in the array that content all nic informations. And as they are not always in the same order, .......

if I remove the \* from received.average: and transmitted.average:, I have the good counter.

I think it can be better to have an options to specify the nic we want.

**Comment by BaldMansMojo** [comment]
I have to drill it down. The performance function is the one from the old op5 plugin.
Can you give me a sample command to see how you check? We here at work don't use this function for network. We have enabled SNMP on all hosts. I have written a plugin to check interface traffic (for all interfaces) by NMP. It works for Windows, Soaris, Linux, NetApp and Vmware. So we the same service defintion (and performance data) for all systems we use

**Comment by ywauthy** [comment]
We check the physical host by SNMP too but for the Virtual Machine we try too only use the vCenter.

I check with this command :
./check_vmware_esx.pl -D vcenter -u 'vcenter_user' -p 'vcenter_password' --S volumes --sessionfiledir /tmp/

In the module vm_net_info.pm. There is this line :

27 $values = return_host_vmware_performance_values($vmname, 'net', ('usage.average:', 'received.average:', 'transmitted.average:'));

The '*' after received.average: and transmitted.average:, get the specified counter for all interfaces. But after in the script, it only keep the last interface in the order they appear in the array. So it is not always the same for each counter.

As we can see in my example : Default interface for counter 143 (net usage) and 148 (net receive). But interface 'vmnic1' for 149 (net send).

**Comment by BaldMansMojo** [comment]
I have to check it. We dont't use Vmware for such thing all machines (physical and virtual) are check in the same manner via SNMP in our scenario. Otherwise you won't have comparable values.

**Comment by BaldMansMojo** [comment]
Sorry for the late answer. It was/is an error from VMware. I can only process the data I get.
