### ISSUE TITLE
Soap API flag responds improperly or documentation is incorrect.

### ISSUE THREAD

**Issue by morgajel** [BaldMansMojo/check_vmware_esx#71]
> SOAP API:
> ---------
> 
> -S, --select=soap                   simple check to verify a successfull connection
>                                     to VMWare SOAP API.

This implies -S and --select=soap are interchangeable. However, when you try to use -S, you get the following error:

``` bash
[user@hostname:/opt/check_vmware_esx]# ./check_vmware_esx.pl -D 192.168.2.3 -f /etc/icinga2/.vmware-credentials -S
Option S requires an argument
Use of uninitialized value $select in lc at ./check_vmware_esx.pl line 1809.
Unknown datacenter select
<contents of help spews out>
```
note that --select=soap does work as intended.
```bash
[user@hostname:/opt/check_vmware_esx]# ./check_vmware_esx.pl -D 192.168.2.3 -f /etc/icinga2/.vmware-credentials --select=soap
OK: Successfully connected to the VMWare SOAP API.
```

**Comment by BaldMansMojo** [comment]
Option S requires an argument!! That means (like in most other unix progams -S soap. As you can see for the whole plugin -S means select and -s means subselect.. No one else hat problems with the syntax before. But for the next release I will rework the help.

**Comment by morgajel** [comment]
gah, nevermind, I wasn't paying attention. please ignore me.
