### ISSUE TITLE
catch maintenance mode

### ISSUE THREAD

**Issue by baramann** [BaldMansMojo/check_vmware_esx#74]
Hi,

is there a way to catch the maintenance mode from a esx and report the system as down?

thanks
bjoern

**Comment by BaldMansMojo** [comment]
The health check does it:

.check_vmware_esx.pl -H vmwarehost  -u username -p password -S runtime -s health
I use with additional
 --ignore_unknown

Regards
Martin

**Comment by baramann** [comment]
Got allways

Notice: esxi6 is in maintenance mode, check skipped

And the state is warning



Von: Martin Fuerstenau [mailto:notifications@github.com]
Gesendet: Mittwoch, 12. August 2015 12:05
An: BaldMansMojo/check_vmware_esx
Cc: Ramann, Björn
Betreff: Re: [check_vmware_esx] catch maintenance mode (#74)


The health check does it:

.check_vmware_esx.pl -H vmwarehost -u username -p password -S runtime -s health
I use with additional
--ignore_unknown

Regards
Martin

**Comment by BaldMansMojo** [comment]
Have I understood you right: If a host is in maintenance mode you will have marked im as down? Right?
