### ISSUE TITLE
Error with --select=runtime at one host: Can' call method "cpuStatusinfo" on an undefined value

### ISSUE THREAD

**Issue by domgre** [BaldMansMojo/check_vmware_esx#77]
Hello,

i've got a problem with one host, the command is the following:

/usr/lib/nagios/plugins/capture_plugin.pl /usr/lib/nagios/plugins/check_vmware_esx/check_vmware_esx.pl -u 'root' -p 'password' --host 192.168.2.182 --select=runtime --nosession
(hte capture_plugin.pl is used to see the output of the script)

Output is: 
Can't call method "cpuStatusInfo" on an undefined value at /usr/lib/nagios/plugins/check_vmware_esx/modules/host_runtime_info.pm line 238.

On another host it is working properly. Ca anyone give me a hint?

**Comment by BaldMansMojo** [comment]
Which Vmware version has the checked host? This can happen if the CIM server of the Vmware doesn't work correctly. Login to your Vcenter and check the behaviour of the server. At a first glance it can be that everything looks ok. But if you look for details you will see, that this is not so. Restarting CIM mostly solves the problem.

Regards
Martin

**Comment by domgre** [comment]
It seems that it's really a problem of the esx, after rebooting it the Console displays no Sensor-Infos, die CIM-Service stops itself. 

I've got another problem which is also esx-relating, the script displays an error with an Memory Module:
1 health issue(s) found in 63 checks: 1) [Critical] [Type: Memory] [Name: Memory] [Label: Unknown] [Summary: The physical element is failing]

This was true, some weeks ago but by the time the module was changed, in HP ILO and in ESX-Console everything is ok. IT seems as if the esx has still stored the error?! A reboot did not help.

**Comment by BaldMansMojo** [comment]
I've found it sometimes tings like this in the past. But the plugin only reports what I get's from Vmware. I had it for example with fibre channel connections. They dismantled the connected discs etc. but they had forgotten to remove the LUNs. So VMware alerted a FC path down. But this is all a Vmware problem. Not a problem of the plugin and therefore I close this issue.
Martin
