### ISSUE TITLE
Why session file stay locked ?

### ISSUE THREAD

**Issue by LeDistordu** [BaldMansMojo/check_vmware_esx#78]
I have a problem each day, session stay locked and i must remove it.

**Comment by BaldMansMojo** [comment]
Well - I think you are nealy the only one with this problem.
- Check the right of the directories and the session files.
- Do you do the check via Vcenter or do you check the hosts directly and only the virtual machines via vcenter.
- Number of service checks?
- Number of waiting checks?
I need some informations. "Mama - it doesnt't work" is unfortunately not enough informations to help you  ;-))
Regards - Martin

**Comment by BaldMansMojo** [comment]
No answer yet. so I close it.
