### ISSUE TITLE
Session file doesn't seem to work

### ISSUE THREAD

**Issue by Knuppes** [BaldMansMojo/check_vmware_esx#79]
Hi,

we are gonna use your script to monitor our brand-new VC6 installation. We made some tests and it work perfect for us.

What we can't get to run is the session file: If we use this, the script initiates a new session every time it connects to VC. So after 10 runs we have 10 sessions open in vc. It doesn't matter if we specify the session file or use the default. Session file is created and looks fine to me.

The only way for us to get around this is the use of --nosession. The the script works.

Any idea?

Cheers

Marco

**Comment by Knuppes** [comment]
After a little bit debugging I made a small change to the script which fixed the problem:

#$url2connect = "https://" . $url2connect . "/sdk/webService";
$url2connect = "https://" . $url2connect . "/sdk";

It seems that the URL has changed from 5.5 to 6.0 or at least the 

Opts::get_option("url")

from the API gives an unexpected string back. Is it easily possible to get around this with a version check before the connect?

**Comment by Anganthier** [comment]
Hi,  
almost same with me. We've go an VC 5.5.0 installation running check_vmware_esx.pl 10 Jun 2015 0.9.26.

I tried without --sessionfile or --sessionfiledir (using default /tmp) and with --sessionfile set to a specific value. The sessionfile do get created and named in the correct location. The sessionfiles are getting locked and unlocked. They are readable and writeable by the correct user:group.

But each request is a new login made in VC. After several minutes the sessions get logged out automatically with only 1 Invocation made.

I am not sure if am doing something wrong. How can I debug the connection/sessionfile usage? The --trace=4 Option does not really help for session file usage debugging.

Bye
Anganthier

**Comment by Knuppes** [comment]
Hi Aganthier,

I'm not a real programmer, just made some printf to look into variables and to see if the code has been passed.

Could you try my workaround with your VC? I would be interested to see if it helps...

**Comment by Anganthier** [comment]
Hi Knuppes,

it looks like I am always hitting the following block. Did just the same using print. 

 eval {Vim::load_session(session_file => $sessionfile_name)};
      if (($@ ne '') || (Opts::get_option("url") ne $url2connect))
         {
         print "Recreating session file\n";
         print Opts::get_option("url") . "\n";
         print $url2connect . "\n";
         unlink $sessionfile_name;
         Util::connect($url2connect, $username, $password);
         Vim::save_session(session_file => $sessionfile_name);
         }

OUTPUT:
Recreating session file
https://vmvc01.stwdo.de/sdk
https://vmvc01.stwdo.de/sdk/webService

I think your code is not just for 6.0. I'll give it a try

Thanks,
Anganthier

**Comment by Anganthier** [comment]
Changed :
#$url2connect = "https://" . $url2connect . "/sdk/webService";
$url2connect = "https://" . $url2connect . "/sdk";
 
OUTPUT:
Loading Session File
OK: Connection state: connected - Power state: poweredOn  - Overall status: green - Console connections: 0 - Guest state: running - Tools state: VMware Tools are installed, running and the version is current. - 0 config issues

Yes, I'll apply that change to production, but it seems that's the problem.

Thanks

**Comment by BaldMansMojo** [comment]
Great. Because I do not have an ESX 6.x here I had no need to use the 6.x SDK. I will see how to fix it in a manner to suit both worlds.
Regards
Martin

**Comment by Knuppes** [comment]
Thanks a lot. Aganthier mentioned, that he uses 5.5. Maybe it's not an version 6 exclusive problem. And maybe it also differs if the vcenter was a blank installation our updated.

Anyway. If you need someone to test your new version against vCenter 6U1, you are welcome...

Cheers

Marco

**Comment by Anganthier** [comment]
VICommon.pm:
use 5.006001;
use strict;
use warnings;

So I am even using an older SDK.

Looking into VMLib.pm I found the following:

if (defined($protocol)) {
            $opt->{value} = "https://" . $server_from_url . "/sdk";
         }
         else {
            $opt->{value} = "http://" . $server_from_url . "/sdk";
         }
in sub get_option.

It would have shown with trace level=5.

Thanks,
Anganthier

**Comment by BaldMansMojo** [comment]
Sorry - not explained well by me. Exixting checks should work with SDK 5.x ans ESX 6.x. It maybe that new features will require SDK 6.x.  When I set up my new Nagios servers some month ago I tried to get SDK 6 to work. Nightmare with Centos 6.x . Due to the fact that i only use ESX 5.x I decided thats 5.x is enough.
Because i have no ESX 6 I hadn't the problem with the URL. I think I will add an additiona switch to the command line to solve this problem.
Regards
Martin

**Comment by schindlerd** [comment]
Hi guys!

I ran into the same problem and spent some time on it. The `$url2connect` variable can be left unchanged. My assumption is that the line 1768:
`if (($@ ne '') || (Opts::get_option("url") ne $url2connect))`
should be adjusted to:
`if ($@ ne '')`

The problem is that `Opts::get_option("url")` always returns "https://**localhost**/sdk/webService" so the condition is that it will always unlink sessionfile and save a new sessionfile.

**Comment by BaldMansMojo** [comment]
Latest plugin version contains an improved version for session management from Sven Nierlein. Should work.
