### ISSUE TITLE
No answer / timeout problem

### ISSUE THREAD

**Issue by Pacman1988** [BaldMansMojo/check_vmware_esx#82]
Hello

I can't start with another user than root the check_vmware_esx script.

As Root:
root@srv-centreon:/usr/lib/nagios/plugins# check_vmware_esx-master/check_vmware_esx.pl -D 172.16.x.x -u username -p "xxx" -S volumes --gigabyte -w 10 -c 5

OK: OK for selected volume(s)...

As User:

centreon-engine@srv-centreon:/usr/lib/nagios/plugins/check_vmware_esx-master$ ./check_vmware_esx.pl -D 172.16.x.x -u username -p "xxx" -S volumes --gigabyte -w 10 -c 5
UNKNOWN: Script timed out.

I uncommented and gave the script the path to the modules: use lib "/usr/lib/nagios/plugins/check_vmware_esx-master/modules";

Do you have any idea? Or how I can debug this failure? Thank you.

**Comment by BaldMansMojo** [comment]
Hi,
seems to be a problem with access rights. In line 1332 is $sessionfile_dir_def defined. In this variable is the directory defined for storing the session files. There may be 2 reasons for this problem:
a) The monitor user has no access
b) The file exists with the wrong user
I think b) will fit. There will be a valid session file (and perhaps a session lock file) but owned by root.. So your monitor user has no access. Change rights or remove the files. Give me a short feedback if it works.

Regards
Martin

**Comment by Pacman1988** [comment]
Yes, it was B.

I deleted in the folder /tmp/ the files 172.16.x.x_session and 172.16.x.x_session_locked.

Great! Thank you for the fast response!

Regards
Marco

**Comment by BaldMansMojo** [comment]
Fine. Just as a hint. Using tmpfs can speed up a lot of things. So all my session files are located on a tmpfs. In case of a rebbot all these files will be recreated with the next login. Same for cache files from plugins. According to my information Centreon is based on 3.x Nagios. I have placed objects.cache and status.dat on tmpfs too. It's like Nitrogen for an engine. Real boost. I use Thruk. It's base on MK livestatus. The socket for livestatus is also on an tmpfs.

Regards - Martin
