### ISSUE TITLE
Can this plugin replace check_vmware_api.pl?

### ISSUE THREAD

**Issue by crazy-canux** [BaldMansMojo/check_vmware_esx#84]
I want to replace check_vmware_api.pl with this plugin.
How to do it?

**Comment by BaldMansMojo** [comment]
The plugin was designed to replace check_vmware_api.pl and it's predecessor.. Best is to read the readme file, the history and the command reference. The reference is the output of --help. Feel free to contact me for samples.

Regards
Martin
