### ISSUE TITLE
VMware connection error - Unknown host select

### ISSUE THREAD

**Issue by wikiaddict** [BaldMansMojo/check_vmware_esx#87]
Good afternoon
Before integrating the plugin with Icinga/Nagios, I'm trying to do some test runs with check_vmware_esx.pl straight from command-line however it's failing to pull any info back from VMware. When running the command, I can see successful login on VMware Host logs. The command is:

perl /usr/lib/nagios/plugins/check_vmware_esx.pl -H IPaddress -u Username -p Password -S volume --sessionfiledir=/tmp/

The reponse is:
Unknown host select

Then pipes out all of the available options.

Any ideas on this one?

**Comment by BaldMansMojo** [comment]
Hi,
first something general. It's not a good idea to mix plugins  "third party" with official ones. You can have several directories. It keeps the house clean.

2nd. No need to call it with perl. Should be executable and the interpreter path (first line of the programm) should direct to the right executable. 

3rd. I think you have a typo. -S volumes and not volume.

It's a ggod idea to have a mouonted tmpfs for the session files. Much more speed.
