### ISSUE TITLE
SOAP request error - possibly a protocol issue: 500 read timeout one 1 of 4 hosts

### ISSUE THREAD

**Issue by bill22152** [BaldMansMojo/check_vmware_esx#88]
./check_vmware_esx.pl -H 172.16.1.11 -S cpu -s usage 
failes

./check_vmware_esx.pl -t100 -H 172.16.1.12-14 -S cpu -s usage 
works

Is there something that should be enabled on host #1?

**Comment by bill22152** [comment]
[root@Nagios bfitzpatrick@lssi.hqmd]# cpan -D Net::HTTP
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.53)
Reading '/root/.local/share/.cpan/Metadata'
  Database was generated on Tue, 05 Apr 2016 20:53:38 GMT
Net::HTTP
-------------------------------------------------------------------------
        CPAN: Module::CoreList loaded ok (v5.20160121)
(no description)
        E/ET/ETHER/Net-HTTP-6.09.tar.gz
        /usr/share/perl5/vendor_perl/Net/HTTP.pm
        Installed: 6.09
        CPAN:      6.09  up to date
        Karen Etheridge (ETHER)
        ether@cpan.org

**Comment by BaldMansMojo** [comment]
Hi,
this seems to be a connection problem ;-)) . The command line tools from Vmware are enclosed with the SDK. First test the connection with the CLI. If this will work the plugin should work (normally). Maybe you haven't set up the local monitor user on that host?

Which ESX versions do you run?

Regards - Martin

**Comment by bill22152** [comment]
The 'esxcli' command works fine on all four hosts.  I did notice that once
I migrated guests off the host the issue moved to another host.

Is it possible it's a load issue or thread count limit? My typical ram
utilization is 40% and the CPU is typically half of that.

**Comment by BaldMansMojo** [comment]
I never heard of such a problem. Can you measure the time for connecting with esxcli for a host the plugin is not working?

**Comment by bill22152** [comment]
The connection with esxcli is instantaneous or nearly.

**Comment by BaldMansMojo** [comment]
As asked earlier: which VSphere version?

**Comment by bill22152** [comment]
Esx 5.5 u2
Vsphere 6

**Comment by BaldMansMojo** [comment]
Am I right - you're running a mix of version 5.5 and 6? have you tested it without session file (--nosession)? Do you use an authfile or submit the user and password?
Does the problem only happens with the check above or with all others?
To seperate a login problem from a check timeout insert in check_vmware_esx.pl in line 1797 (after the login part before the trace part) a
print "Here we are\n";
So if you test from the command line you will see the message. If this happens fast the problem is not based on login. It's based on server response.
If you use the plugin in production us a copy of check_vmware_esx.pl for the test.

Regards - martin

**Comment by bill22152** [comment]
I've had mixed results with session files
And I use username password

Let me test with no session and your 'I'm here' version.

Bill

**Comment by BaldMansMojo** [comment]
Session files - these are important. Otherwise you will have a lot of login/logout in your Logfiles. In case of problems with sessionfiles it's mostly an incorrect setup. But for testing it can be wise to disable as much as possible.

Martin

**Comment by ramkomatlapalli** [comment]
Is the issue resolved, if so share me the same. Even i am having the same issue.

Error that I got

CoCHECK_VMWARE_API.PL CRITICALSOAP request error - possibly a protocol issue: 500 read timeout

I use esxi 6.7 and managed by vcenter 6.7

**Comment by BaldMansMojo** [comment]
Unfortunately I can't reproduce it. Use latest version from Plugin. It contains a lot of changes and improvements.
