### ISSUE TITLE
Pending result and xml format comes out

### ISSUE THREAD

**Issue by loewechiu** [BaldMansMojo/check_vmware_esx#95]
Hi Guru,

I use below command but after executing it, results will come out  after a long time and with xml format information, also with a SOAP request error at the beginning.
./check_vmware_esx.pl -u root -p mypass -H 10.134.140.2 -S io

My environment is:
Ubuntu 14.04
SDK 5.5

But I missed one perl module as I couldn't install it.
cpan[2]>  install File::Basename
Running install for module 'File::Basename'
The most recent version "2.85" of the module "File::Basename"
is part of the perl-5.24.0 distribution. To install that, you need to run
  force install File::Basename   --or--
  install R/RJ/RJBS/perl-5.24.0.tar.gz
Failed during this command:
 RJBS/perl-5.24.0.tar.gz                      : make NO isa perl

Thank you very much.

**Comment by BaldMansMojo** [comment]
This is not an issue of the plugin. It's an issue of an incorrect installed SDK I think. Please test first with the CLI tools from the SDK. If these are working correctly the plugin should work too.

I will close this issue for now. Fee free to reopen it if there's a problem with the plugin.

Martin
