### ISSUE TITLE
Cluster -C doesnt work for me.

### ISSUE THREAD

**Issue by denisimmoos** [BaldMansMojo/check_vmware_esx#97]
Hi there

In a multi cluster environment the following command doesn't work.

It always takes the first ESX host and not the ESX where the Cudtomers environment is on 

 ./check_vmware_esx.pl -H 10.122.20.35 -f ./auth  -C 'Customer Basel' -S runtime
OK: 0/7 VMs suspended - 0/7 VMs powered off - 7/7 VMs powered on - overallstatus=green - connection state=connected - All 103 health checks are GREEN: System (1x), system (1x), Platform Alert (1x), CPU (2x), voltage (31x), Processors (18x), Memory (1x), other (17x), power (11x), temperature (20x) - 0 config issues  - 0 config issues ignored

<a href='https://postimg.org/image/e4uvsh4br/' target='_blank'><img src='https://s31.postimg.org/e4uvsh4br/29_07_2016_11_14_36.png' border='0' alt='postimage'/></a>

How can this be solved ?

Thank You

**Comment by BaldMansMojo** [comment]
Sorry - cluster is not finished yet (and has some bugs). It was buggy in the original version too. When I cleaned up the code from check_vmware_api.pl I kicked out a lot of unnecessary stuff. But it's not ready. This month I will be on vacation, in September I have to do my annual tax decleration. So I hope that I will find the time to publish all unpublished fixes etc. (a lot from the community but not tested by me) in November. Next will rewriting the cluster part and adding monitoring of resource groups etc.

I will leave this issue open so i can't forget it.

Beste Grüsse nach Basel aus München
Martin

**Comment by denisimmoos** [comment]
Hallo BaldManMojo 
Ich hoffe, die jährlichen Steuererklährungen tragen nicht zur "Baldness" bei ... ;) Meine hat mich auch Haare gekostet :) ... Vielen Dank für die Info und viel Spass in den Ferien ... https://www.youtube.com/watch?v=r660AcCnC6Y

**Comment by zitzman** [comment]
Is Cluster not working yet?

Not sure id doing it correctly. 
Suppose:
vcenter server fqdn is: myvcenter.mydomain
datacenter name is: mydatacenter
cluster under this data center is: mycluster

When running:
./check_vmware_esx -D myvcenter.mydomain -u icinga@vsphere.local -p mypassword --cluster='mycluster' -S cluster 

I get:
SOAP Fault:
-----------
Fault string: A specified parameter was not correct: querySpec.interval
Fault detail: InvalidArgumentFault

**Comment by mettworks** [comment]
I get the error below, is this related to this task? 

check_vmware_esx.pl --gigabyte --datacenter $hostname --cluster 'Production' -u User -p Password  -S runtime

Can't use string ("Production") as a HASH ref while "strict refs" in use at /usr/local/Serverplugins//hamburg/check_vmware_esx_vcenter/check_vmware_esx.pl line 2592.

**Comment by zrhck** [comment]
Hi,

is there any chance that the fixes will be published?

**Comment by BaldMansMojo** [comment]
Sorry. Cluster part is still unfinished buggy old stuff from op5. I have to spent some work on it.
