### ISSUE TITLE
Can't kill a non-​numeric process ID

### ISSUE THREAD

**Issue by Tontonitch** [BaldMansMojo/check_vmware_esx#98]
Hi,
I'm facing the same kind of issue as #43 and #89 . 
For one of my esx, the session file seems to be "corrupted".
Consequently, I receive the message 

> Can't kill a non-​numeric process ID at /usr/lib64/nagios/plugins/check_​vmware_​esx line 1744. 

for all the checks on that esx.
All the others are ok.

Looking at the session files, indeed, something happened with session file "vspheremgmt_sessionfile_esx62.dat_session". It is indeed empty now, and a "_locked" file exist now.

```
[root@monitorsrv1 ~]# ls -larth /var/spool/nagios/check_vmware_esx/
total 16K
drwxrwxrwx 7 icinga icinga  121 Aug 23 12:34 ..
-rw-r--r-- 1 icinga icinga    0 Aug 30 20:29 vspheremgmt_sessionfile_esx62.dat_session_locked
-rw------- 1 icinga icinga    0 Aug 30 20:29 vspheremgmt_sessionfile_esx62.dat_session
-rw------- 1 icinga icinga  178 Aug 31 09:04 vspheremgmt_sessionfile_DEV.dat_session
-rw------- 1 icinga icinga  178 Aug 31 09:05 vspheremgmt_sessionfile_esx61.dat_session
-rw------- 1 icinga icinga  178 Aug 31 09:05 vspheremgmt_sessionfile_esx60.dat_session
drwxrwxr-x 2 icinga icinga 4.0K Aug 31 09:05 .
[root@monitorsrv1 ~]#
[root@monitorsrv1 ~]# more /var/spool/nagios/check_vmware_esx/vspheremgmt_sessionfile_esx62.dat_session_locked
[root@monitorsrv1 ~]# more /var/spool/nagios/check_vmware_esx/vspheremgmt_sessionfile_esx62.dat_session
[root@monitorsrv1 ~]#
```

Removing the files corrected the situation.

Might it be a solution to make that the plugin automatically remove such a problematic empty session file?

Best regards,
Yannick

**Comment by BaldMansMojo** [comment]
Good idea. I have several changes to do but unfortunately I had not enough time. I will implement all of this during the next weeks.

Best regards
Martin

**Comment by Tontonitch** [comment]
Hi Martin,
Great to see that a solution would be implemented!
I had again a similar problem with session file, but a bit different as the session file was not empty:
```
[root@monitorsrv1 ~]# ls -larth /var/spool/nagios/check_vmware_esx/
total 20K
drwxrwxrwx 7 icinga icinga  121 Aug 23 12:34 ..
-rw------- 1 icinga icinga  178 Sep  7 22:42 vspheremgmt_sessionfile_esx62.dat_session
-rw-r--r-- 1 icinga icinga    0 Sep  7 22:43 vspheremgmt_sessionfile_esx62.dat_session_locked
-rw------- 1 icinga icinga  178 Sep  8 17:13 vspheremgmt_sessionfile_DEV.dat_session
-rw------- 1 icinga icinga  178 Sep  8 17:13 vspheremgmt_sessionfile_esx61.dat_session
-rw------- 1 icinga icinga  178 Sep  8 17:13 vspheremgmt_sessionfile_esx60.dat_session
drwxrwxr-x 2 icinga icinga 4.0K Sep  8 17:13 .
[root@monitorsrv1 ~]#
```
As you can see the lock file was not removed, maybe because of an issue with a check_vmware_esx launched process. Indeed, I'm facing some load issue on that server and sometimes it produce strange behavior with the running processes.
Removing the lock file fixed the situation.

So, what could be good also is to remove the lock file when it seems to be old (or in this case to remove the session file also to be sure that it will be recreated and be ok).

Best regards,
Yannick

**Comment by BaldMansMojo** [comment]
Hi Yannick,

this is (normally not necessary) because the PID of the job created the lockfile is within the lockfile. So my plugin takes the PID and looks for the process. If there is no process with this PID the lockfile will be removed. I think I will changed it in the manner that a lockfile with a nonnumric PID or without a PID will be removed anyway.

Regards - Martin

**Comment by zhihongsun51** [comment]
I think my pull request fixes this problem.

**Comment by BaldMansMojo** [comment]
Maybe. Currently I'm ill at home. I will check it next week. I think this can happen not too often. The kill won't kill. It checks for a running process. So this situation can only happen when the process locking the session has termintaed but the the lockfile has'nt been changed.

Regards - Martin

**Comment by BaldMansMojo** [comment]
Merged most pull request plus some other changes. Should work now.

Regards
Martin
